// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq8A-KR4d5JMeAD6Ag7Lmu8Y3K3c5ab9o',
    appId: '1:1022657305934:web:e8757713dae76b162c521f',
    messagingSenderId: '1022657305934',
    projectId: 'nuevadb-2b0a3',
    authDomain: 'nuevadb-2b0a3.firebaseapp.com',
    storageBucket: 'nuevadb-2b0a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHo7K8tLoNrAsW6RDJm1_KVa7wUdE81Zc',
    appId: '1:1022657305934:android:d21db7e59bc7e1662c521f',
    messagingSenderId: '1022657305934',
    projectId: 'nuevadb-2b0a3',
    storageBucket: 'nuevadb-2b0a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Lv1rBXdRLzrzVK-xD2YTN_0slBwghoA',
    appId: '1:1022657305934:ios:e4302ed2d4b6c79f2c521f',
    messagingSenderId: '1022657305934',
    projectId: 'nuevadb-2b0a3',
    storageBucket: 'nuevadb-2b0a3.appspot.com',
    iosClientId: '1022657305934-3mn23v2hivtt37f9429uem0ll4k276e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Lv1rBXdRLzrzVK-xD2YTN_0slBwghoA',
    appId: '1:1022657305934:ios:d25f52a9f655b5402c521f',
    messagingSenderId: '1022657305934',
    projectId: 'nuevadb-2b0a3',
    storageBucket: 'nuevadb-2b0a3.appspot.com',
    iosClientId: '1022657305934-qo1eqtjveomr8phh5ucnpa6il6gkisth.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp.RunnerTests',
  );
}
